name: GitHub Actions Demo
on: 
  push:
    branches:
      - main
      - develop
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Run dev
      run: ./gradlew clean build -Pbuild=dev
    - name: Unit tests
      run: ./gradlew testDebugUnitTest --stacktrace
    - name: Ui Test
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 23
        target: default
        arch: x86
        profile: Nexus 6
        script: ./gradlew connectedDebugAndroidTest --stacktrace
